// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace template.biz.Entities
{
    public partial class CatCoberturaCodigoPostal
    {
        public int Id { get; set; }
        public string Codigo { get; set; }
        public bool? Viaticos { get; set; }
        public decimal? Costo { get; set; }
    }
}