// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace template.biz.Entities
{
    public partial class CatUnidadesPorEquipo
    {
        public int Id { get; set; }
        public int UnMinimoUnidad { get; set; }
        public int UnMaximoUnidad { get; set; }
        public int UnMinimoEquipo { get; set; }
        public int UnMaximoEquipo { get; set; }
        public int? Catpromocionid { get; set; }

        public virtual Promocion Catpromocion { get; set; }
    }
}