// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace template.biz.Entities
{
    public partial class NotificacionesComerciales
    {
        public int Id { get; set; }
        public string Titulo { get; set; }
        public string Cuerpo { get; set; }
        public string UrlImagen { get; set; }
        public DateTime? Fecha { get; set; }
        public string Hora { get; set; }
        public string Url { get; set; }
    }
}