// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace template.biz.Entities
{
    public partial class NotificationApp
    {
        public int Id { get; set; }
        public long? UserId { get; set; }
        public string UidEquipo { get; set; }
        public string Token { get; set; }
        public bool? Notification { get; set; }
        public string NameEquipo { get; set; }

        public virtual Users User { get; set; }
    }
}