// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace template.biz.Entities
{
    public partial class RelTecnicoVisitaApp
    {
        public int Id { get; set; }
        public long IdTecnico { get; set; }
        public long IdVista { get; set; }
        public bool TecnicoResponsable { get; set; }

        public virtual Tecnicos IdTecnicoNavigation { get; set; }
        public virtual VisitaApp IdVistaNavigation { get; set; }
    }
}