// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace template.biz.Entities
{
    public partial class RelUserUserApp
    {
        public int Id { get; set; }
        public long? IdClient { get; set; }
        public long? IdClientApp { get; set; }
    }
}