// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace template.biz.Entities
{
    public partial class ServicioFotosApp
    {
        public int Id { get; set; }
        public string UrlFoto { get; set; }
        public long? IdVisitaApp { get; set; }

        public virtual VisitaApp IdVisitaAppNavigation { get; set; }
    }
}