// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace template.biz.Entities
{
    public partial class VisitaApp
    {
        public VisitaApp()
        {
            RelServicioCategoriaApp = new HashSet<RelServicioCategoriaApp>();
            RelTecnicoVisitaApp = new HashSet<RelTecnicoVisitaApp>();
            ServicioFotosApp = new HashSet<ServicioFotosApp>();
        }

        public long Id { get; set; }
        public long? Tecnicosid { get; set; }
        public string ActividadesRealizar { get; set; }
        public bool? AsignacionRefacciones { get; set; }
        public decimal Cantidad { get; set; }
        public string Comprobante { get; set; }
        public string Concepto { get; set; }
        public bool? EntregaRefacciones { get; set; }
        public int? Estatus { get; set; }
        public bool Factura { get; set; }
        public string FechaDeposito { get; set; }
        public DateTime FechaEntregaRefaccion { get; set; }
        public DateTime? FechaFinVisita { get; set; }
        public DateTime? FechaInicioVisita { get; set; }
        public DateTime FechaVisita { get; set; }
        public bool Garantia { get; set; }
        public string Hora { get; set; }
        public string HoraFin { get; set; }
        public int IdDireccion { get; set; }
        public long IdServicio { get; set; }
        public string ImagenFirma { get; set; }
        public string ImagenPagoReferenciado { get; set; }
        public string LatitudFin { get; set; }
        public string LatitudInicio { get; set; }
        public string LongitudFin { get; set; }
        public string LongitudInicio { get; set; }
        public string NoOperacion { get; set; }
        public bool Pagado { get; set; }
        public bool PagoPendiente { get; set; }
        public bool? PreDiagnostico { get; set; }
        public bool? SiAceptoTecnicoRefaccion { get; set; }
        public bool TerminosCondiciones { get; set; }
        public string PersonaRecibe { get; set; }
        public DateTime? FechaAgendado { get; set; }
        public string UrlPpdfReporte { get; set; }
        public string FechaLimitePago { get; set; }
        public string FecPago { get; set; }
        public string IdPago { get; set; }
        public string SuccesPago { get; set; }
        public DateTime FechaCancelacion { get; set; }
        public string MotivaCancelación { get; set; }
        public string UrlPdfChecklist { get; set; }
        public string UrlPdfCotizacion { get; set; }
        public string UrlPdfConfirmacionVisita { get; set; }
        public DateTime FechaCompletado { get; set; }
        public string MotivaCompletado { get; set; }

        public virtual ServicioApp IdServicioNavigation { get; set; }
        public virtual ICollection<RelServicioCategoriaApp> RelServicioCategoriaApp { get; set; }
        public virtual ICollection<RelTecnicoVisitaApp> RelTecnicoVisitaApp { get; set; }
        public virtual ICollection<ServicioFotosApp> ServicioFotosApp { get; set; }
    }
}